import { useEffect, useState } from 'react';
import { attractionCommerceAPI } from '../../../api/generation';

export default function SessionAttractionCommercePanel({ sessionId, attractionId }) {
  const [itinerary, setItinerary] = useState([]); const [inclusions, setInclusions] = useState([]); const [name, setName] = useState(''); const [included, setIncluded] = useState('');
  const load = async () => { if (!sessionId || !attractionId) return; const [a, b] = await Promise.all([attractionCommerceAPI.listItinerary(sessionId, attractionId), attractionCommerceAPI.listInclusions(sessionId, attractionId)]); setItinerary(a.data?.results || []); setInclusions(b.data?.results || []); };
  useEffect(() => { load().catch(() => {}); }, [sessionId, attractionId]);
  return <div className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-gray-200 p-3"><p className="mb-2 text-sm font-semibold">Маршрут гида</p>{itinerary.map((x) => <p key={x.id} className="text-sm text-gray-600">• {x.name?.ru || x.name?.en || 'Без названия'}</p>)}<div className="mt-2 flex gap-2"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Новая точка" className="min-w-0 flex-1 rounded border px-2 py-1 text-sm"/><button type="button" onClick={async()=>{if(name.trim()){await attractionCommerceAPI.addItinerary(sessionId, attractionId,{name:{ru:name}});setName('');load();}}} className="rounded bg-blue-600 px-2 text-sm text-white">+</button></div></div><div className="rounded-lg border border-gray-200 p-3"><p className="mb-2 text-sm font-semibold">Что включено</p>{inclusions.map((x) => <p key={x.id} className="text-sm text-gray-600">{x.kind === 'included' ? '✓' : '✗'} {x.text?.ru || x.text?.en || '—'}</p>)}<div className="mt-2 flex gap-2"><input value={included} onChange={(e) => setIncluded(e.target.value)} placeholder="Новый пункт" className="min-w-0 flex-1 rounded border px-2 py-1 text-sm"/><button type="button" onClick={async()=>{if(included.trim()){await attractionCommerceAPI.addInclusion(sessionId, attractionId,{kind:'included',text:{ru:included}});setIncluded('');load();}}} className="rounded bg-blue-600 px-2 text-sm text-white">+</button></div></div></div>;
}
